adding homework#13
ValentynaVel/robot_dreams pull request #13
Opened 2023-02-20 14:38 UTC by ValentynaVel

2023-02-26 15:29 UTC, klymenok requested changes
There is no solutions for home work

2023-02-26 15:55 UTC, ValentynaVel commented
I just updated PR because files was empty.

2023-02-26 17:04 UTC, klymenok requested changes

2023-02-26 17:04 UTC, klymenok commented on homework13_3.py
> +query = ("SELECT age, COUNT(id) FROM users GROUP BY age")
To have the output as it asked in the task, you should use alias here for the aggregated amount: ` ... , COUNT(id) as users FROM ...`

2023-02-26 17:04 UTC, klymenok commented on homework13_4.py
> +query = ("SELECT age, COUNT(id) FROM users GROUP BY age ORDER BY COUNT(id), age desc")
You can use alias here for COUNT(id) and order by the alias: `... COUNT(id) as users ... ORDER BY users.

And pay attention: you should order by users in descending order and by age in ascending

2023-02-28 20:29 UTC, klymenok approved these changes
Looks good!

2023-03-02 14:18 UTC, merged