adding homework for lesson 27
ValentynaVel/robot_dreams pull request #16
Opened 2023-03-23 23:16 UTC by ValentynaVel

Hello. I added homework for lesson 27. But there are some problems in the code, which I cannot solve.

2023-03-24 21:43 UTC, klymenok requested changes

2023-03-24 21:43 UTC, klymenok commented on 27/js.js
> +  paragraph.innerText = `${paragraphName} ${rand+1}`;
Змінної paragraph не існує в цій області видимості. Вам потрібно ініціалізувати її, після чого ви зможете змінити її значення.

2023-03-24 21:43 UTC, klymenok commented on 27/js.js
> +['Кількість друзів '].map(paragraphName => {
`map` це функція масивів і її доцільно використовувати тоді, коли ви працюєте з масивом даних. У вашому випадку це одне значення і воно не обовʼязково має міститися в масиві. Винесіть весь цей код з map і використайте значення "Кількість друзів" як звичайне значення
```
...
paragraph.innerText = `Кількість друзів ${rand}`
...

2023-03-24 21:43 UTC, klymenok commented on 27/js.js
> +const btn = document.getElementById('1')[0];
getElementById повертає один обʼєкт, а не масив. Тому не потрібно тут брати елемент за індексом, так як це не масив: `const btn = document.getElementById('1')`

2023-04-11 19:48 UTC, ValentynaVel commented on 27/js.js
> +const btn = document.getElementById('1')[0];
Передивилась ще раз лекцію та виправила код.

2023-04-11 20:26 UTC, klymenok approved these changes
Looks good!

2023-04-12 08:54 UTC, merged