homework #30
ValentynaVel/robot_dreams pull request #17
Opened 2023-04-02 13:59 UTC by ValentynaVel

2023-04-06 17:35 UTC, klymenok requested changes

2023-04-06 17:35 UTC, klymenok commented on 30/hw30_1.py
> +lst_url = [gl, fb, tw, am, ap]
Вам не обовʼязково створювати окремі змінні і потім їх поміщати в list, оскільки ви їх після цього ніде не використовуєте. Можете в list помістити одразу значення, ось так, наприклад:
```
lst_url = [
    "https://www.google.co.uk/",
    "https://www.facebook.com/".
    "https://twitter.com/".
    "https://www.amazon.co.uk/",
    "https://www.apple.com/",
]

2023-04-06 17:35 UTC, klymenok commented on 30/hw30_1.py
> +print(res.status_code)
Крім status code вам також потрібно надрукувати тут назву зайту і довжину HTML коду із відповіді

2023-04-06 17:35 UTC, klymenok commented on 30/30_2.py
> +API_key = 'bb9afbcf5556e45bba9c7109de792691'
НЕ РОБІТЬ ТАК НІКОЛИ.

Дуже погана практика зберігати ключі прямо в коді і пушити їх. В прикладі до ДЗ було дане API, що працює без ключів. Щодо цього, то ключ краще розмістити в env, або залишити тут пусте значення із коментарем, що користувач має використовувати власний API KEY, отриманий із цього сервісу

2023-04-06 17:35 UTC, klymenok commented on 30/30_2.py
> +            print(f"Hourly temperature in {city_name}: {current_weather['temperature_2m']}°C")
По завданню вам потрібно було виводити поточні показники погоди, тобто погоду на зараз. Щоб отримати поточні показники, ви можете додати до url відповідні query params (`*current_weather=true`), і у відповіді оримаєте окремо поточні показники

2023-04-10 13:11 UTC, merged

2023-04-11 19:58 UTC, ValentynaVel commented on 30/hw30_1.py
> +lst_url = [gl, fb, tw, am, ap]
Виправила