sending homework #34
ValentynaVel/robot_dreams pull request #23
Opened 2023-04-20 14:38 UTC by ValentynaVel

2023-04-20 20:22 UTC, klymenok requested changes

2023-04-20 20:22 UTC, klymenok commented on flask-homework/views.py
> +        username = session['username']
У вас не працює жодна сторінка тому що ви записуєте в сесію `user`, а перевіряєте на наявність `username`

2023-04-20 20:22 UTC, klymenok commented on flask-homework/templates/user.html
> +		<p>404 - User not found</p>
Вам потрібно редіректити на сторінку 404 або просто повертати цей код в якості відповіді, але не хардкодити цю поведінку в темплейті

2023-04-21 08:14 UTC, ValentynaVel commented on flask-homework/views.py
> +        username = session['username']
дякую, виправила

2023-04-24 09:21 UTC, ValentynaVel commented on flask-homework/templates/user.html
> +		<p>404 - User not found</p>
виправила

2023-04-25 17:48 UTC, klymenok requested changes
Looks good!

2023-04-26 08:09 UTC, merged