creating django application
ValentynaVel/robot_dreams pull request #25
Opened 2023-05-02 11:26 UTC by ValentynaVel

homework #38

2023-05-03 11:07 UTC, klymenok requested changes

2023-05-03 11:07 UTC, klymenok commented on django/robot/settings.py
> +SECRET_KEY = 'django-insecure-zcgbavcu$l$@89t-cwo1t0%3!)7l((h!im^t@m7ro+^^)t=a+k'
Винесіть SECRET_KEY в .env

2023-05-03 11:07 UTC, klymenok commented on django/user/migrations/__pycache__/__init__.cpython-311.pyc
Не пуште на репозиторій директорії __pychache__

2023-05-03 14:01 UTC, ValentynaVel commented on django/robot/settings.py
> +SECRET_KEY = 'django-insecure-zcgbavcu$l$@89t-cwo1t0%3!)7l((h!im^t@m7ro+^^)t=a+k'
Виправила

2023-05-03 14:01 UTC, ValentynaVel commented on django/user/migrations/__pycache__/__init__.cpython-311.pyc
Добре видалю її тут

2023-05-08 09:43 UTC, klymenok approved these changes

2023-05-09 21:29 UTC, merged