Adding models and endpoints task39
ValentynaVel/robot_dreams pull request #26
Opened 2023-05-03 15:03 UTC by ValentynaVel

2023-05-08 10:03 UTC, klymenok requested changes

2023-05-08 10:03 UTC, klymenok commented on django/robot/urls.py
> +    path('books/', include('book.urls')),
Файлу book/urls.py не існує

2023-05-08 10:03 UTC, klymenok commented on django/robot/urls.py
> +    path('purchases/', include('purchase.urls')),
те саме тут - файлу не існує

2023-05-08 10:03 UTC, klymenok commented on django/book/models.py
> +class Book(models.Model):
Для моделей потрібно створити міграції

2023-05-08 10:03 UTC, klymenok commented on django/purchase/views.py
> +            'user_id': purchase.user_id,
Оскільки поля модедей у вас називаються user_id та book_id, щоб отримати доступ саме до id повʼязаних обʼєктів вам потрібно додати до імен цих полей суфікс `_id`:
```
    'user_id': purchase.user_id_id,
    'book_id': purchase.book_id_id
```

Але я б радив вам переіменувати поля моделей відповідно на `user` та `book`. 
Тоді `purchase.user` буде містити обʼєкт повʼязаного User, а до id можна буде звернутися як `purchase.user_id` або `purchase.user.id`

2023-05-10 13:04 UTC, ValentynaVel commented on django/robot/urls.py
> +    path('books/', include('book.urls')),
Додала файл в git

2023-05-10 13:05 UTC, ValentynaVel commented on django/robot/urls.py
> +    path('purchases/', include('purchase.urls')),
Додала файл в git

2023-05-11 12:44 UTC, ValentynaVel commented on django/book/models.py
> +class Book(models.Model):
зробила makemigrations та migrate

2023-05-11 12:44 UTC, ValentynaVel commented on django/purchase/views.py
> +            'user_id': purchase.user_id,
виправила

2023-05-11 16:28 UTC, klymenok commented on django/book/models.py
> +class Book(models.Model):
Додайте файли міграцій на git (я їх тут не бачу)

2023-05-11 16:28 UTC, klymenok commented on django/purchase/views.py
> +            'user_id': purchase.user_id,
Вам потрібно або назву атрибуту змінити на `purchase.user_id_id`, або назву атрибуту в моделі змінити на user
```
class Purchase(models.Model):
    date = models.DateField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
```

2023-05-11 16:29 UTC, klymenok commented on django/book/models.py
> +class Book(models.Model):
Додайте файли міграцій на git (я їх тут не бачу)

2023-05-11 16:30 UTC, klymenok requested changes

2023-05-11 16:30 UTC, klymenok commented on django/book/__pycache__/__init__.cpython-311.pyc
Постарайтесь не пушити __pychache__ на git

2023-05-11 17:07 UTC, ValentynaVel commented on django/book/models.py
> +class Book(models.Model):
Додала файли міграцій

2023-05-12 08:15 UTC, ValentynaVel commented on django/purchase/views.py
> +            'user_id': purchase.user_id,
Дякую. Виправила.

2023-05-12 08:22 UTC, ValentynaVel commented on django/book/__pycache__/__init__.cpython-311.pyc
Добре. Більше не буду їх відправляти на git.

2023-05-12 10:19 UTC, klymenok approved these changes

2023-05-12 11:01 UTC, merged